### ISSUE TITLE
remove BMD options for user-interface

### ISSUE THREAD

**Issue by shapiromatron** [shapiromatron/hawc#97]
We currently don't have a public BMD webserver for me to run jobs on, so for the time being, so comment-out the "run bmd analysis" options at the endpoint-level. Hopefully we'll have another server in the near future.

**Comment by shapiromatron** [comment]
@shanethacker this won't negatively impact you, right? That is, you currently don't have a separate  [BMDS server](https://github.com/shapiromatron/bmds-server/) operational, right?

**Comment by shanethacker** [comment]
We actually do, although I don't remember if I ever got it working correctly. I haven't heard any complaints, but that could happen from people not using it. I'd say go ahead and remove it, though, because we're about to face the challenge of BMDS 3.0, and I'd like to see if people are actually using it in HAWC before we have to adapt to the new version.

**Comment by shapiromatron** [comment]
@shanethacker hmm, I don't want to remove if you might have possible users? Would you mind checking to see if you have any BMD results?

```python
from bmd.models import Session
Session.objects.count()
```

I think BMDSv3 is a long way away too... it'd be great to get this version in the hands for your team if you have it working...

**Comment by shanethacker** [comment]
@shapiromatron Looks like we've got three records. One from March, from hawcproject.org, one from July for ours, and one from last night, of all things. No results, as far as I can tell. Looks like I need to go back into our server and see if I can get it working.

As I recall, I got the web interface up, but I don't think it was running the jobs. Now I can't get to the web interface either. Could be some update since the last time I was working on it. Our ORD servers tend to get victimized by random uninstalls. I'll run through the instructions again.

**Comment by shapiromatron** [comment]
Not surprised about the bmds-server; i'm having a hard time deploying it on windows and am still working on it.  Given that this is the case, I'm going to go ahead and remove the bmds from hawc for now. If you get it working we can revisit; I suspect this is only a temporary change for a few months however since I just found resources to redeploy my bmds server again...

**Comment by shapiromatron** [comment]
See #117 for recent updates.
